### ISSUE TITLE
New Task: Scope the management of milestones and tasks within the repo

### ISSUE THREAD

**Issue by laurabrenskelle** [ioos/marine_life_data_network#13]
### Who is requesting this?

@MathewBiddle and @laurabrenskelle

### What is being requested?

Review GitHub uses for [milestones ](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) and possibly [task lists](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists). Determine a workflow for managing Marine Life tasks in a format that allows for related issues to be grouped into milestones.

### What is the requested deadline and why?

04-26-2024 to give us some time given the Marine Biological Data Mobilization Workshop is April 22-24

### What is the current status quo (i.e., what happens if this does not get done)?

This will allow us to create a hierarchical structure of related tasks and show progress toward overarching milestones.

**Comment by laurabrenskelle** [comment]
I made this milestone as an example: https://github.com/ioos/marine_life_data_network/milestone/1

We could make separate issues for the different tag types and group them under this milestone so the progress of this effort could be tracked.
- Automate ingestion of SPOT style tags to ADR
- Automate ingestion of PAT tags to ADR
- Automate ingestion of GPS tags to ADR
- Automate ingestion of CTD/CTD-F and temperature only profiling tags to ADR
- Automate ingestion of Lotek marine tags to ADR

**Comment by MathewBiddle** [comment]
Seeing all those acronyms make me 😵 . We need to build an acronym definition list.

I like where this is headed. Would the milestone have the date associated with it? Or, would we try to set dates on an issue by issue basis?

I like how you included the description of the milestone. This should be the why is this important statement, I think.

**Comment by laurabrenskelle** [comment]
Yeah, an acronym list would be helpful. I'm sure @mmckinzie could help with that.

I think the milestone could have a date associated. Our hoped-for deadline? Within the Project, we/Axiom could use the box that shows up on the right side of the screen in issues to enter start and end dates for issues?

Yes, I think the description of the milestone should be what it is and why it's important.

**Comment by laurabrenskelle** [comment]
Tangential to this issue, but I made a draft of a glossary document in my own fork: https://github.com/laurabrenskelle/marine_life_data_network/blob/main/glossary.md

I think it is a good start for formatting, but I am unsure if I like the Reference (if any) part of the table.

**Comment by dpsnowden** [comment]
@MathewBiddle @laurabrenskelle I think it's important to put dates on milestones.  Issues can sometimes drag on for month and months and I think it's important to identify an approximate date that you hope to wrap up the milestone (and hence the issue).  When I review a project I tend to look for the past due things first since that's usually a sign that the project needs some help.  It's also a good signal to potential contributors that this project is healthy and moving forward and worth their time investment.

When thinking about issue scope, try to keep them manageable and able to be completed.  In my experience issues that are never finished are usually those that start out with a very vague definition of done and a huge goal.  

I like where this is going and encourage you to keep using this as the way to manage the project as an open source project that invites external contributions while also keeping our funded work focused.  Thx!!!

**Comment by MathewBiddle** [comment]
Current implementation:
* Milestones == 9 core tasks 
* issues == multitude of sub-tasks related to the 9 core tasks

**Comment by conniekot** [comment]
Going through the process for the first time in adding 1 whole milestone with 4 tasks (woo!), I had some questions/suggestions but none absolutely pressing:
To simplify entering tasks (good job, so far!) and anticipating what info is what is most important (what and when):
- Maybe revisit if we need to have "why" and just provide the "why" info if necessary in the last catchall section? This would make this section easier to scan (provided we follow the same date format, could suggest format in template if necessary)
 - Maybe revisit if we need "What is the current status quo (i.e., what happens if this does not get done)?" and move to last catchall section (could add it as a suggestion if that is something you commonly include)

**Comment by MathewBiddle** [comment]
@lmshowalter3 Let us know what works for you too

**Comment by MathewBiddle** [comment]
I ran across this recently too https://docs.github.com/en/issues/managing-your-tasks-with-tasklists/about-tasklists

**Comment by MathewBiddle** [comment]
@laurabrenskelle this is done. I'm closing for now, but reopen if we need to explore this more.
