### ISSUE TITLE
[New Task]: MBON: Add NANOOS zooplankton data from OBIS to MBON portal

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/marine_life_data_network#5]
### Who is requesting this?

@emiliom

### What is being requested?

NANOOS would like to add to MBON the OBIS dataset we recently published on OBIS: "Zooplankton densities collected from a seasonally hypoxic fjord (Hood Canal, Salish Sea, USA) on 2012-2013 cruises", https://obis.org/dataset/5463caa4-b929-477f-ae6c-7007b6d91baa Matt Biddle pointed me here to get the process started (see https://github.com/ioos/bio_data_guide/issues/168#issuecomment-1973862090).

### What is the timeline for the completion of this task?

~1 month??

### Provide a description or any other important information.

I am testing this issue template and seeing how far we want to take this tracking process.

Ref: https://mbon.ioos.us/?ls=-DPD0g_0

**Comment by emiliom** [comment]
> What is the timeline for the completion of this task?
>
> ~1 month??

Is that *our* desired timeline, or your estimated timeline? On our end, I don't think we have a specific timeline in mind, other than wanting to see "steady" progress or at least a reasonably clear estimated timeline on your end.

**Comment by MathewBiddle** [comment]
@lmshowalter3 let's go ahead an add these data into the MBON Data Portal. Please reach out if you have any questions. Thanks!

**Comment by lmshowalter3** [comment]
Jira ticket exists for this ingest. Will update when progress is made.

**Comment by emiliom** [comment]
> This study identified all zooplankton but focused on krill, so the focus on the one copepod species is okay.

This might be ambiguous. To be clear: for our dataset we can focus on 1-3 species, preferably >1 if not too crowded. One of them will definitely be `euphausia pacifica` (Pacific krill). The others are likely to be the [next most common taxa in the dataset](https://obis.org/dataset/5463caa4-b929-477f-ae6c-7007b6d91baa), but I'll get back to you on that once we know how many species can be displayed.

Thanks!

**Comment by emiliom** [comment]
Checking in to see if any progress has been made, even if just in figuring out a time frame. Thanks.

**Comment by MathewBiddle** [comment]
Thank you for your patience @emiliom! This has been in the staging portal for some time now, I just slipped on sending the link. Check out the dataset on the staging portal: https://mbon.ioos.us/?ls=7g901PVJ#map

FYI, we are currently evaluating the MBON Data Portal and it's usefulness to the community. So, things may change in the future.

**Comment by emiliom** [comment]
Thanks @MathewBiddle ! Perfect timing. We have a meeting this Friday to discuss the [other, much larger (and ongoing) Puget Sound zooplankton dataset](https://github.com/ioos/bio_data_guide/issues/260) that we've been working on this year. In this meeting there'll be a couple of scientists who want to learn more about what happens to the data once it's published to OBIS, and I know they'll be very happy to see this MBON Data Portal preview for the Hood Canal dataset.

What's on the staging portal looks great! I'll follow up with consensus feedback from the group after Friday. On my first look, I'd say the "Depth Range (m)" drop-down filter is pretty useless, because nearly every depth interval is unique. On the other hand, the time and depth selectors at the bottom of the screen are fantastic, and the depth selector in particular does exactly what I'd want.

**Comment by iwensu0313** [comment]
Hi @emiliom! (I've taken over data support for this ticket from the Axiom side). Thanks for the initial input - was there additional feedback on the data visualization provided at the meeting last Friday?

**Comment by emiliom** [comment]
@iwensu0313 sorry for the late response. I see that the "Depth Range (m)" drop-down filter has already been removed. Thanks! 

The only other comment I have is about the numbers next to each item in each drop down. For example, under Location: `Dabob (1)`. I don't know what those numbers are. I would expect them to be some sort of count, but the only counts that would make sense to me are of samples or occurrences, and that's definitely not what I'm seeing. Could you explain what they are? Can they be easily hidden, to avoid confusion?

Otherwise, I think it's good to go!

**Comment by emiliom** [comment]
Thanks for the clarification. Given that it's easy to hide those numbers, yeah, I think it's best to do so.

After that, let's make it live!

**Comment by iwensu0313** [comment]
@emiliom great! We hid the numbers and the data catalog page is now live on the MBON portal here: https://mbon.ioos.us/#module-metadata/fd29d4a3-277d-4743-9088-0773bcc14176

(@MathewBiddle completing this ticket)

**Comment by emiliom** [comment]
Wonderful, thank you!

Is there a link we can use to send users directly to the live data portal with the dataset loaded? That is, the equivalent of this short link, but for the live portal: https://mbon.ioos.us/?ls=7g901PVJ#map
